repos:
- repo: local
  hooks:
    - id: run-ci
      name: Run CI checks
      entry: just precommit
      language: script
      always_run: true
      pass_filenames: false
      stages: [commit, push]
